// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWPRIiRECQMFDSuV1WUNvlggIjGnTSv9g',
    appId: '1:79924350725:web:4c26e21b54d20ae845716c',
    messagingSenderId: '79924350725',
    projectId: 'test2-aba24',
    authDomain: 'test2-aba24.firebaseapp.com',
    storageBucket: 'test2-aba24.appspot.com',
    measurementId: 'G-17FVLJN3WY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtqd1Hw5CkY02qtaWRLvHkSJQy2XaLko4',
    appId: '1:79924350725:android:6d4a58489246cf7c45716c',
    messagingSenderId: '79924350725',
    projectId: 'test2-aba24',
    storageBucket: 'test2-aba24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2urVP21FiY1qPq52_WhOPMtB8Ve3et6w',
    appId: '1:79924350725:ios:02d05a67e9866dab45716c',
    messagingSenderId: '79924350725',
    projectId: 'test2-aba24',
    storageBucket: 'test2-aba24.appspot.com',
    iosClientId: '79924350725-l81rblfiemh7d50vdf9986nrt55jijji.apps.googleusercontent.com',
    iosBundleId: 'com.example.testapp',
  );
}
